//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplication_ProximaGen.WS_Client {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Client.WS_ProximaGenSoap")]
    public interface WS_ProximaGenSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AgregarEstado(string descripcionEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AgregarEstadoAsync(string descripcionEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ModificarEstado(int idEstado, string descripcionEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ModificarEstadoAsync(int idEstado, string descripcionEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EliminarEstado(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarEstadoAsync(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerEstados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LeerEstados(int inicio, int final);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerEstados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LeerEstadosAsync(int inicio, int final);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ProximaGenSoapChannel : WebAplication_ProximaGen.WS_Client.WS_ProximaGenSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ProximaGenSoapClient : System.ServiceModel.ClientBase<WebAplication_ProximaGen.WS_Client.WS_ProximaGenSoap>, WebAplication_ProximaGen.WS_Client.WS_ProximaGenSoap {
        
        public WS_ProximaGenSoapClient() {
        }
        
        public WS_ProximaGenSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ProximaGenSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProximaGenSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProximaGenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet AgregarEstado(string descripcionEstado) {
            return base.Channel.AgregarEstado(descripcionEstado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AgregarEstadoAsync(string descripcionEstado) {
            return base.Channel.AgregarEstadoAsync(descripcionEstado);
        }
        
        public System.Data.DataSet ModificarEstado(int idEstado, string descripcionEstado) {
            return base.Channel.ModificarEstado(idEstado, descripcionEstado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ModificarEstadoAsync(int idEstado, string descripcionEstado) {
            return base.Channel.ModificarEstadoAsync(idEstado, descripcionEstado);
        }
        
        public System.Data.DataSet EliminarEstado(int idEstado) {
            return base.Channel.EliminarEstado(idEstado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarEstadoAsync(int idEstado) {
            return base.Channel.EliminarEstadoAsync(idEstado);
        }
        
        public System.Data.DataSet LeerEstados(int inicio, int final) {
            return base.Channel.LeerEstados(inicio, final);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LeerEstadosAsync(int inicio, int final) {
            return base.Channel.LeerEstadosAsync(inicio, final);
        }
    }
}
